[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --prefix ./backend"]

[phases.build]
cmds = ["npm run build --prefix ./backend"]

[start]
cmd = "npm start --prefix ./backend"
